# Generated by Django 5.0.6 on 2024-07-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("download_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name_plural": ""},
        ),
    ]
