# Generated by Django 5.0.6 on 2024-07-08 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0002_userdownload_alter_subscription_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={},
        ),
    ]
